[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
sim-lib = { path = "../sim-lib" }
femtovg = "0.13.0"
glutin = "0.31.0"
glutin-winit = "0.4.0"
raw-window-handle = "0.5.0"
winit = { version = "0.29.1" }
num_cpus = "1.16.0"
